# Generated by Django 2.2.12 on 2021-02-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=110),
        ),
    ]
