# Generated by Django 2.2.12 on 2021-02-04 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('marca', models.CharField(db_index=True, default='', max_length=50)),
                ('imagem', models.CharField(blank=True, max_length=150)),
                ('disponivel', models.BooleanField(blank=True, default=True)),
                ('preco', models.DecimalField(decimal_places=2, default=3.99, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('profundidade', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('unidadesPorCaixa', models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=5)),
                ('unidadeDeVenda', models.CharField(blank=True, default='un', max_length=15)),
                ('multiploDeVenda', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5)),
                ('descricao', models.TextField(blank=True, default='', max_length=800)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('categoria', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categoria.Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
                'ordering': ('codigo', 'nome'),
            },
        ),
    ]
