# Generated by Django 2.2.12 on 2021-02-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20210204_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='informacoesTecnicas',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='produto',
            name='pesoBruto',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
