# Generated by Django 2.2.12 on 2021-02-05 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20210204_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('codigo', 'nome'), 'permissions': (('administrativo', 'Pode administrar os produtos'),), 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
