# Generated by Django 2.2.12 on 2021-02-08 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_auto_20210205_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='informacoesTecnicas',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
